env:
  IMAGE_NAME: apache/gobblin
jobs:
  build_and_push_to_registry:
    name: Build docker images and publish to DockerHub
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out the repo
      uses: actions/checkout@v2
    - continue-on-error: true
      id: build_tag
      name: Build Docker Tag
      run: "SHA=`echo ${{ github.sha }} | head -c 7`\nif [[ ${{ github.event_name\
        \ }} == 'release' ]]; then\n  TAG=\"${{ env.IMAGE_NAME }}:sha-$SHA, ${{ env.IMAGE_NAME\
        \ }}:${{ github.event.release.tag_name }}, ${{ env.IMAGE_NAME }}:latest\"\n\
        else\n  TAG=\"${{ env.IMAGE_NAME }}:sha-$SHA\"\nfi\necho \"tag=$TAG\"\necho\
        \ \"::set-output name=tag::$TAG\"\n"
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USER }}
    - continue-on-error: true
      name: Build Images and Publish
      uses: docker/build-push-action@v2
      with:
        file: ./gobblin-docker/gobblin/alpine-gobblin-latest/Dockerfile
        push: false
        tags: ${{ steps.build_tag.outputs.tag }}
name: Build and Publish Docker image
on:
  repository_dispatch:
    types: trigger-ga___docker_build_publish.yaml
